kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgpods-bkup-volume
  namespace: com-jasmit-pgpods
  labels:
    app: pgpods-bkup
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /opt/app/pgpods/storage/bkup
  persistentVolumeReclaimPolicy: Retain
