kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgpods-base-claim
  namespace: com-jasmit-pgpods
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      app: pgpods-base
