kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgpods-xlog-volume
  namespace: com-jasmit-pgpods
  labels:
    app: pgpods-xlog
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /opt/app/pgpods/storage/xlog
  persistentVolumeReclaimPolicy: Retain
