kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgpods-data-volume
  namespace: com-jasmit-pgpods
  labels:
    app: pgpods-data
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /opt/app/pgpods/storage/data
  persistentVolumeReclaimPolicy: Retain
