kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgpods-base-volume
  namespace: com-jasmit-pgpods
  labels:
    app: pgpods-base
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /opt/app/pgpods/storage/base
  persistentVolumeReclaimPolicy: Retain
