kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc 
  namespace: postgres 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 16Gi
