#
#  volume.yaml
#
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-volume 
  namespace: postgres 
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" 
  local: 
    path: /System/Volumes/Data/opt/app/postgres/data 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lima-rancher-desktop
  claimRef:
    name: postgres-volume-claim-postgres-statefulset-0 
    namespace: postgres





# spec:
#   capacity:
#     storage: 16Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: "" 
#   local: 
#     path: /System/Volumes/Data/opt/app/postgres/data 
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - lima-rancher-desktop
#   claimRef:
#     name: postgres-volume-claim-postgres-statefulset-0 
#     namespace: postgres
